apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: clusterissuer-coffeeapp
  namespace: dev
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: mmmbiloniya@gmail.com
    privateKeySecretRef:
      name: coffeeapp-app
    solvers:
    - http01:
        ingress:
          class: nginx