apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: coffeeapp-app
  namespace: dev
spec:
  secretName: coffeeapp-app
  issuerRef:
    name: clusterissuer-coffeeapp
    kind: ClusterIssuer
  commonName: kubesimplify.xyz
  dnsNames:
  - kubesimplify.xyz
  - inventory.kubesimplify.xyz
  - prometheus.kubesimplify.xyz
  - grafana.kubesimplify.xyz