apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
  labels:
    app: prometheus
    environment: devops
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'inventory-application'
        metrics_path: '/actuator/prometheus'
        static_configs:
        - targets: ['inventory-service.dev.svc.cluster.local']

      - job_name: 'order-application'
        metrics_path: '/actuator/prometheus'
        static_configs:
        - targets: ['order-service.dev.svc.cluster.local']

      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
          - role: node

      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod

      - job_name: 'kubernetes-services'
        kubernetes_sd_configs:
          - role: service

      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics.dev.svc.cluster.local:8080']
