server:
  port: 8082

inventory:
  espresso-shot: ${espresso-shot}
  milk: ${milk}
  milk-foam: ${milk-foam}
  hot-water: ${hot-water} # Use a large value to indicate "unlimited"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  # endpoint:
  #   prometheus:
  #     enabled: true
  # server:
  #   port: 8081  # Optional: Change port to expose metrics on a separate port

