apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-certificate
  namespace: argocd
spec:
  secretName: argocd-certificate
  issuerRef:
    name: clusterissuer-argocd
    kind: ClusterIssuer
  commonName: kubesimplify.xyz
  dnsNames:
  - argocd.kubesimplify.xyz
