apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: clusterissuer-argocd
  namespace: argocd
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: mmmbiloniya@gmail.com
    privateKeySecretRef:
      name: argocd-certificate
    solvers:
    - http01:
        ingress:
          class: nginx